/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardGamificationRewardsRouteImport } from './routes/dashboard/gamification/rewards'
import { Route as DashboardGamificationRedemptionsRouteImport } from './routes/dashboard/gamification/redemptions'
import { Route as DashboardGamificationParticipationApprovalsRouteImport } from './routes/dashboard/gamification/participation-approvals'
import { Route as DashboardGamificationLeaderboardRouteImport } from './routes/dashboard/gamification/leaderboard'
import { Route as DashboardGamificationChallengesRouteImport } from './routes/dashboard/gamification/challenges'
import { Route as DashboardGamificationBadgesRouteImport } from './routes/dashboard/gamification/badges'
import { Route as DashboardEnvironmentalSustainabilityGoalsRouteImport } from './routes/dashboard/environmental/sustainability-goals'
import { Route as DashboardEnvironmentalProductEsgProfilesRouteImport } from './routes/dashboard/environmental/product-esg-profiles'
import { Route as DashboardEnvironmentalOverviewRouteImport } from './routes/dashboard/environmental/overview'
import { Route as DashboardEnvironmentalEmissionFactorsRouteImport } from './routes/dashboard/environmental/emission-factors'
import { Route as DashboardEnvironmentalCarbonTransactionsRouteImport } from './routes/dashboard/environmental/carbon-transactions'
import { Route as DashboardAdministrationNotificationSettingsRouteImport } from './routes/dashboard/administration/notification-settings'
import { Route as DashboardAdministrationEsgConfigurationRouteImport } from './routes/dashboard/administration/esg-configuration'
import { Route as DashboardAdministrationDepartmentsRouteImport } from './routes/dashboard/administration/departments'
import { Route as DashboardAdministrationCategoriesRouteImport } from './routes/dashboard/administration/categories'

const ForgetPasswordLazyRouteImport = createFileRoute('/forget-password')()
const AuthLazyRouteImport = createFileRoute('/auth')()
const DashboardSettingsLazyRouteImport = createFileRoute(
  '/dashboard/settings',
)()
const AuthSignupLazyRouteImport = createFileRoute('/auth/signup')()
const AuthLoginLazyRouteImport = createFileRoute('/auth/login')()

const ForgetPasswordLazyRoute = ForgetPasswordLazyRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forget-password.lazy').then((d) => d.Route),
)
const AuthLazyRoute = AuthLazyRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardSettingsLazyRoute = DashboardSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings.lazy').then((d) => d.Route),
)
const AuthSignupLazyRoute = AuthSignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/signup.lazy').then((d) => d.Route))
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))
const DashboardGamificationRewardsRoute =
  DashboardGamificationRewardsRouteImport.update({
    id: '/gamification/rewards',
    path: '/gamification/rewards',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGamificationRedemptionsRoute =
  DashboardGamificationRedemptionsRouteImport.update({
    id: '/gamification/redemptions',
    path: '/gamification/redemptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGamificationParticipationApprovalsRoute =
  DashboardGamificationParticipationApprovalsRouteImport.update({
    id: '/gamification/participation-approvals',
    path: '/gamification/participation-approvals',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGamificationLeaderboardRoute =
  DashboardGamificationLeaderboardRouteImport.update({
    id: '/gamification/leaderboard',
    path: '/gamification/leaderboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGamificationChallengesRoute =
  DashboardGamificationChallengesRouteImport.update({
    id: '/gamification/challenges',
    path: '/gamification/challenges',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGamificationBadgesRoute =
  DashboardGamificationBadgesRouteImport.update({
    id: '/gamification/badges',
    path: '/gamification/badges',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnvironmentalSustainabilityGoalsRoute =
  DashboardEnvironmentalSustainabilityGoalsRouteImport.update({
    id: '/environmental/sustainability-goals',
    path: '/environmental/sustainability-goals',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnvironmentalProductEsgProfilesRoute =
  DashboardEnvironmentalProductEsgProfilesRouteImport.update({
    id: '/environmental/product-esg-profiles',
    path: '/environmental/product-esg-profiles',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnvironmentalOverviewRoute =
  DashboardEnvironmentalOverviewRouteImport.update({
    id: '/environmental/overview',
    path: '/environmental/overview',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnvironmentalEmissionFactorsRoute =
  DashboardEnvironmentalEmissionFactorsRouteImport.update({
    id: '/environmental/emission-factors',
    path: '/environmental/emission-factors',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnvironmentalCarbonTransactionsRoute =
  DashboardEnvironmentalCarbonTransactionsRouteImport.update({
    id: '/environmental/carbon-transactions',
    path: '/environmental/carbon-transactions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdministrationNotificationSettingsRoute =
  DashboardAdministrationNotificationSettingsRouteImport.update({
    id: '/administration/notification-settings',
    path: '/administration/notification-settings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdministrationEsgConfigurationRoute =
  DashboardAdministrationEsgConfigurationRouteImport.update({
    id: '/administration/esg-configuration',
    path: '/administration/esg-configuration',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdministrationDepartmentsRoute =
  DashboardAdministrationDepartmentsRouteImport.update({
    id: '/administration/departments',
    path: '/administration/departments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdministrationCategoriesRoute =
  DashboardAdministrationCategoriesRouteImport.update({
    id: '/administration/categories',
    path: '/administration/categories',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/administration/categories': typeof DashboardAdministrationCategoriesRoute
  '/dashboard/administration/departments': typeof DashboardAdministrationDepartmentsRoute
  '/dashboard/administration/esg-configuration': typeof DashboardAdministrationEsgConfigurationRoute
  '/dashboard/administration/notification-settings': typeof DashboardAdministrationNotificationSettingsRoute
  '/dashboard/environmental/carbon-transactions': typeof DashboardEnvironmentalCarbonTransactionsRoute
  '/dashboard/environmental/emission-factors': typeof DashboardEnvironmentalEmissionFactorsRoute
  '/dashboard/environmental/overview': typeof DashboardEnvironmentalOverviewRoute
  '/dashboard/environmental/product-esg-profiles': typeof DashboardEnvironmentalProductEsgProfilesRoute
  '/dashboard/environmental/sustainability-goals': typeof DashboardEnvironmentalSustainabilityGoalsRoute
  '/dashboard/gamification/badges': typeof DashboardGamificationBadgesRoute
  '/dashboard/gamification/challenges': typeof DashboardGamificationChallengesRoute
  '/dashboard/gamification/leaderboard': typeof DashboardGamificationLeaderboardRoute
  '/dashboard/gamification/participation-approvals': typeof DashboardGamificationParticipationApprovalsRoute
  '/dashboard/gamification/redemptions': typeof DashboardGamificationRedemptionsRoute
  '/dashboard/gamification/rewards': typeof DashboardGamificationRewardsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/administration/categories': typeof DashboardAdministrationCategoriesRoute
  '/dashboard/administration/departments': typeof DashboardAdministrationDepartmentsRoute
  '/dashboard/administration/esg-configuration': typeof DashboardAdministrationEsgConfigurationRoute
  '/dashboard/administration/notification-settings': typeof DashboardAdministrationNotificationSettingsRoute
  '/dashboard/environmental/carbon-transactions': typeof DashboardEnvironmentalCarbonTransactionsRoute
  '/dashboard/environmental/emission-factors': typeof DashboardEnvironmentalEmissionFactorsRoute
  '/dashboard/environmental/overview': typeof DashboardEnvironmentalOverviewRoute
  '/dashboard/environmental/product-esg-profiles': typeof DashboardEnvironmentalProductEsgProfilesRoute
  '/dashboard/environmental/sustainability-goals': typeof DashboardEnvironmentalSustainabilityGoalsRoute
  '/dashboard/gamification/badges': typeof DashboardGamificationBadgesRoute
  '/dashboard/gamification/challenges': typeof DashboardGamificationChallengesRoute
  '/dashboard/gamification/leaderboard': typeof DashboardGamificationLeaderboardRoute
  '/dashboard/gamification/participation-approvals': typeof DashboardGamificationParticipationApprovalsRoute
  '/dashboard/gamification/redemptions': typeof DashboardGamificationRedemptionsRoute
  '/dashboard/gamification/rewards': typeof DashboardGamificationRewardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/administration/categories': typeof DashboardAdministrationCategoriesRoute
  '/dashboard/administration/departments': typeof DashboardAdministrationDepartmentsRoute
  '/dashboard/administration/esg-configuration': typeof DashboardAdministrationEsgConfigurationRoute
  '/dashboard/administration/notification-settings': typeof DashboardAdministrationNotificationSettingsRoute
  '/dashboard/environmental/carbon-transactions': typeof DashboardEnvironmentalCarbonTransactionsRoute
  '/dashboard/environmental/emission-factors': typeof DashboardEnvironmentalEmissionFactorsRoute
  '/dashboard/environmental/overview': typeof DashboardEnvironmentalOverviewRoute
  '/dashboard/environmental/product-esg-profiles': typeof DashboardEnvironmentalProductEsgProfilesRoute
  '/dashboard/environmental/sustainability-goals': typeof DashboardEnvironmentalSustainabilityGoalsRoute
  '/dashboard/gamification/badges': typeof DashboardGamificationBadgesRoute
  '/dashboard/gamification/challenges': typeof DashboardGamificationChallengesRoute
  '/dashboard/gamification/leaderboard': typeof DashboardGamificationLeaderboardRoute
  '/dashboard/gamification/participation-approvals': typeof DashboardGamificationParticipationApprovalsRoute
  '/dashboard/gamification/redemptions': typeof DashboardGamificationRedemptionsRoute
  '/dashboard/gamification/rewards': typeof DashboardGamificationRewardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth'
    | '/forget-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/administration/categories'
    | '/dashboard/administration/departments'
    | '/dashboard/administration/esg-configuration'
    | '/dashboard/administration/notification-settings'
    | '/dashboard/environmental/carbon-transactions'
    | '/dashboard/environmental/emission-factors'
    | '/dashboard/environmental/overview'
    | '/dashboard/environmental/product-esg-profiles'
    | '/dashboard/environmental/sustainability-goals'
    | '/dashboard/gamification/badges'
    | '/dashboard/gamification/challenges'
    | '/dashboard/gamification/leaderboard'
    | '/dashboard/gamification/participation-approvals'
    | '/dashboard/gamification/redemptions'
    | '/dashboard/gamification/rewards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forget-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/administration/categories'
    | '/dashboard/administration/departments'
    | '/dashboard/administration/esg-configuration'
    | '/dashboard/administration/notification-settings'
    | '/dashboard/environmental/carbon-transactions'
    | '/dashboard/environmental/emission-factors'
    | '/dashboard/environmental/overview'
    | '/dashboard/environmental/product-esg-profiles'
    | '/dashboard/environmental/sustainability-goals'
    | '/dashboard/gamification/badges'
    | '/dashboard/gamification/challenges'
    | '/dashboard/gamification/leaderboard'
    | '/dashboard/gamification/participation-approvals'
    | '/dashboard/gamification/redemptions'
    | '/dashboard/gamification/rewards'
  id:
    | '__root__'
    | '/dashboard'
    | '/auth'
    | '/forget-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/administration/categories'
    | '/dashboard/administration/departments'
    | '/dashboard/administration/esg-configuration'
    | '/dashboard/administration/notification-settings'
    | '/dashboard/environmental/carbon-transactions'
    | '/dashboard/environmental/emission-factors'
    | '/dashboard/environmental/overview'
    | '/dashboard/environmental/product-esg-profiles'
    | '/dashboard/environmental/sustainability-goals'
    | '/dashboard/gamification/badges'
    | '/dashboard/gamification/challenges'
    | '/dashboard/gamification/leaderboard'
    | '/dashboard/gamification/participation-approvals'
    | '/dashboard/gamification/redemptions'
    | '/dashboard/gamification/rewards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLazyRoute: typeof AuthLazyRouteWithChildren
  ForgetPasswordLazyRoute: typeof ForgetPasswordLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forget-password': {
      id: '/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof ForgetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/dashboard/gamification/rewards': {
      id: '/dashboard/gamification/rewards'
      path: '/gamification/rewards'
      fullPath: '/dashboard/gamification/rewards'
      preLoaderRoute: typeof DashboardGamificationRewardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gamification/redemptions': {
      id: '/dashboard/gamification/redemptions'
      path: '/gamification/redemptions'
      fullPath: '/dashboard/gamification/redemptions'
      preLoaderRoute: typeof DashboardGamificationRedemptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gamification/participation-approvals': {
      id: '/dashboard/gamification/participation-approvals'
      path: '/gamification/participation-approvals'
      fullPath: '/dashboard/gamification/participation-approvals'
      preLoaderRoute: typeof DashboardGamificationParticipationApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gamification/leaderboard': {
      id: '/dashboard/gamification/leaderboard'
      path: '/gamification/leaderboard'
      fullPath: '/dashboard/gamification/leaderboard'
      preLoaderRoute: typeof DashboardGamificationLeaderboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gamification/challenges': {
      id: '/dashboard/gamification/challenges'
      path: '/gamification/challenges'
      fullPath: '/dashboard/gamification/challenges'
      preLoaderRoute: typeof DashboardGamificationChallengesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gamification/badges': {
      id: '/dashboard/gamification/badges'
      path: '/gamification/badges'
      fullPath: '/dashboard/gamification/badges'
      preLoaderRoute: typeof DashboardGamificationBadgesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/environmental/sustainability-goals': {
      id: '/dashboard/environmental/sustainability-goals'
      path: '/environmental/sustainability-goals'
      fullPath: '/dashboard/environmental/sustainability-goals'
      preLoaderRoute: typeof DashboardEnvironmentalSustainabilityGoalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/environmental/product-esg-profiles': {
      id: '/dashboard/environmental/product-esg-profiles'
      path: '/environmental/product-esg-profiles'
      fullPath: '/dashboard/environmental/product-esg-profiles'
      preLoaderRoute: typeof DashboardEnvironmentalProductEsgProfilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/environmental/overview': {
      id: '/dashboard/environmental/overview'
      path: '/environmental/overview'
      fullPath: '/dashboard/environmental/overview'
      preLoaderRoute: typeof DashboardEnvironmentalOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/environmental/emission-factors': {
      id: '/dashboard/environmental/emission-factors'
      path: '/environmental/emission-factors'
      fullPath: '/dashboard/environmental/emission-factors'
      preLoaderRoute: typeof DashboardEnvironmentalEmissionFactorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/environmental/carbon-transactions': {
      id: '/dashboard/environmental/carbon-transactions'
      path: '/environmental/carbon-transactions'
      fullPath: '/dashboard/environmental/carbon-transactions'
      preLoaderRoute: typeof DashboardEnvironmentalCarbonTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/administration/notification-settings': {
      id: '/dashboard/administration/notification-settings'
      path: '/administration/notification-settings'
      fullPath: '/dashboard/administration/notification-settings'
      preLoaderRoute: typeof DashboardAdministrationNotificationSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/administration/esg-configuration': {
      id: '/dashboard/administration/esg-configuration'
      path: '/administration/esg-configuration'
      fullPath: '/dashboard/administration/esg-configuration'
      preLoaderRoute: typeof DashboardAdministrationEsgConfigurationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/administration/departments': {
      id: '/dashboard/administration/departments'
      path: '/administration/departments'
      fullPath: '/dashboard/administration/departments'
      preLoaderRoute: typeof DashboardAdministrationDepartmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/administration/categories': {
      id: '/dashboard/administration/categories'
      path: '/administration/categories'
      fullPath: '/dashboard/administration/categories'
      preLoaderRoute: typeof DashboardAdministrationCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardSettingsLazyRoute: typeof DashboardSettingsLazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdministrationCategoriesRoute: typeof DashboardAdministrationCategoriesRoute
  DashboardAdministrationDepartmentsRoute: typeof DashboardAdministrationDepartmentsRoute
  DashboardAdministrationEsgConfigurationRoute: typeof DashboardAdministrationEsgConfigurationRoute
  DashboardAdministrationNotificationSettingsRoute: typeof DashboardAdministrationNotificationSettingsRoute
  DashboardEnvironmentalCarbonTransactionsRoute: typeof DashboardEnvironmentalCarbonTransactionsRoute
  DashboardEnvironmentalEmissionFactorsRoute: typeof DashboardEnvironmentalEmissionFactorsRoute
  DashboardEnvironmentalOverviewRoute: typeof DashboardEnvironmentalOverviewRoute
  DashboardEnvironmentalProductEsgProfilesRoute: typeof DashboardEnvironmentalProductEsgProfilesRoute
  DashboardEnvironmentalSustainabilityGoalsRoute: typeof DashboardEnvironmentalSustainabilityGoalsRoute
  DashboardGamificationBadgesRoute: typeof DashboardGamificationBadgesRoute
  DashboardGamificationChallengesRoute: typeof DashboardGamificationChallengesRoute
  DashboardGamificationLeaderboardRoute: typeof DashboardGamificationLeaderboardRoute
  DashboardGamificationParticipationApprovalsRoute: typeof DashboardGamificationParticipationApprovalsRoute
  DashboardGamificationRedemptionsRoute: typeof DashboardGamificationRedemptionsRoute
  DashboardGamificationRewardsRoute: typeof DashboardGamificationRewardsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsLazyRoute: DashboardSettingsLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdministrationCategoriesRoute:
    DashboardAdministrationCategoriesRoute,
  DashboardAdministrationDepartmentsRoute:
    DashboardAdministrationDepartmentsRoute,
  DashboardAdministrationEsgConfigurationRoute:
    DashboardAdministrationEsgConfigurationRoute,
  DashboardAdministrationNotificationSettingsRoute:
    DashboardAdministrationNotificationSettingsRoute,
  DashboardEnvironmentalCarbonTransactionsRoute:
    DashboardEnvironmentalCarbonTransactionsRoute,
  DashboardEnvironmentalEmissionFactorsRoute:
    DashboardEnvironmentalEmissionFactorsRoute,
  DashboardEnvironmentalOverviewRoute: DashboardEnvironmentalOverviewRoute,
  DashboardEnvironmentalProductEsgProfilesRoute:
    DashboardEnvironmentalProductEsgProfilesRoute,
  DashboardEnvironmentalSustainabilityGoalsRoute:
    DashboardEnvironmentalSustainabilityGoalsRoute,
  DashboardGamificationBadgesRoute: DashboardGamificationBadgesRoute,
  DashboardGamificationChallengesRoute: DashboardGamificationChallengesRoute,
  DashboardGamificationLeaderboardRoute: DashboardGamificationLeaderboardRoute,
  DashboardGamificationParticipationApprovalsRoute:
    DashboardGamificationParticipationApprovalsRoute,
  DashboardGamificationRedemptionsRoute: DashboardGamificationRedemptionsRoute,
  DashboardGamificationRewardsRoute: DashboardGamificationRewardsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthLazyRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthSignupLazyRoute: typeof AuthSignupLazyRoute
}

const AuthLazyRouteChildren: AuthLazyRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthSignupLazyRoute: AuthSignupLazyRoute,
}

const AuthLazyRouteWithChildren = AuthLazyRoute._addFileChildren(
  AuthLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthLazyRoute: AuthLazyRouteWithChildren,
  ForgetPasswordLazyRoute: ForgetPasswordLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
