/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ForgetPasswordLazyRouteImport = createFileRoute('/forget-password')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const AuthLazyRouteImport = createFileRoute('/auth')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardSettingsLazyRouteImport = createFileRoute(
  '/dashboard/settings',
)()
const AuthSignupLazyRouteImport = createFileRoute('/auth/signup')()
const AuthLoginLazyRouteImport = createFileRoute('/auth/login')()

const ForgetPasswordLazyRoute = ForgetPasswordLazyRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forget-password.lazy').then((d) => d.Route),
)
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const AuthLazyRoute = AuthLazyRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardSettingsLazyRoute = DashboardSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings.lazy').then((d) => d.Route),
)
const AuthSignupLazyRoute = AuthSignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/signup.lazy').then((d) => d.Route))
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/forget-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forget-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/auth'
    | '/dashboard'
    | '/forget-password'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLazyRoute: typeof AuthLazyRouteWithChildren
  DashboardLazyRoute: typeof DashboardLazyRouteWithChildren
  ForgetPasswordLazyRoute: typeof ForgetPasswordLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forget-password': {
      id: '/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof ForgetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
  }
}

interface AuthLazyRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthSignupLazyRoute: typeof AuthSignupLazyRoute
}

const AuthLazyRouteChildren: AuthLazyRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthSignupLazyRoute: AuthSignupLazyRoute,
}

const AuthLazyRouteWithChildren = AuthLazyRoute._addFileChildren(
  AuthLazyRouteChildren,
)

interface DashboardLazyRouteChildren {
  DashboardSettingsLazyRoute: typeof DashboardSettingsLazyRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
}

const DashboardLazyRouteChildren: DashboardLazyRouteChildren = {
  DashboardSettingsLazyRoute: DashboardSettingsLazyRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
}

const DashboardLazyRouteWithChildren = DashboardLazyRoute._addFileChildren(
  DashboardLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLazyRoute: AuthLazyRouteWithChildren,
  DashboardLazyRoute: DashboardLazyRouteWithChildren,
  ForgetPasswordLazyRoute: ForgetPasswordLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
