/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSocialTrainingCompletionRouteImport } from './routes/dashboard/social/training-completion'
import { Route as DashboardSocialOverviewRouteImport } from './routes/dashboard/social/overview'
import { Route as DashboardSocialEmployeeParticipationRouteImport } from './routes/dashboard/social/employee-participation'
import { Route as DashboardSocialDiversityMetricsRouteImport } from './routes/dashboard/social/diversity-metrics'
import { Route as DashboardGovernancePolicyAcknowledgementsRouteImport } from './routes/dashboard/governance/policy-acknowledgements'
import { Route as DashboardGovernanceOverviewRouteImport } from './routes/dashboard/governance/overview'
import { Route as DashboardGamificationRewardsRouteImport } from './routes/dashboard/gamification/rewards'
import { Route as DashboardGamificationRedemptionsRouteImport } from './routes/dashboard/gamification/redemptions'
import { Route as DashboardGamificationParticipationApprovalsRouteImport } from './routes/dashboard/gamification/participation-approvals'
import { Route as DashboardGamificationLeaderboardRouteImport } from './routes/dashboard/gamification/leaderboard'
import { Route as DashboardGamificationChallengesRouteImport } from './routes/dashboard/gamification/challenges'
import { Route as DashboardGamificationBadgesRouteImport } from './routes/dashboard/gamification/badges'
import { Route as DashboardEnvironmentalSustainabilityGoalsRouteImport } from './routes/dashboard/environmental/sustainability-goals'
import { Route as DashboardEnvironmentalProductEsgProfilesRouteImport } from './routes/dashboard/environmental/product-esg-profiles'
import { Route as DashboardEnvironmentalOverviewRouteImport } from './routes/dashboard/environmental/overview'
import { Route as DashboardEnvironmentalEmissionFactorsRouteImport } from './routes/dashboard/environmental/emission-factors'
import { Route as DashboardEnvironmentalCarbonTransactionsRouteImport } from './routes/dashboard/environmental/carbon-transactions'
import { Route as DashboardAdministrationNotificationSettingsRouteImport } from './routes/dashboard/administration/notification-settings'
import { Route as DashboardAdministrationEsgConfigurationRouteImport } from './routes/dashboard/administration/esg-configuration'
import { Route as DashboardAdministrationDepartmentsRouteImport } from './routes/dashboard/administration/departments'
import { Route as DashboardAdministrationCategoriesRouteImport } from './routes/dashboard/administration/categories'
import { Route as DashboardSocialCsrActivitiesIndexRouteImport } from './routes/dashboard/social/csr-activities/index'
import { Route as DashboardGovernancePoliciesIndexRouteImport } from './routes/dashboard/governance/policies/index'
import { Route as DashboardGovernanceComplianceIssuesIndexRouteImport } from './routes/dashboard/governance/compliance-issues/index'
import { Route as DashboardGovernanceAuditsIndexRouteImport } from './routes/dashboard/governance/audits/index'
import { Route as DashboardSocialCsrActivitiesActivityIdRouteImport } from './routes/dashboard/social/csr-activities/$activityId'
import { Route as DashboardGovernancePoliciesPolicyIdRouteImport } from './routes/dashboard/governance/policies/$policyId'
import { Route as DashboardGovernanceComplianceIssuesIssueIdRouteImport } from './routes/dashboard/governance/compliance-issues/$issueId'
import { Route as DashboardGovernanceAuditsAuditIdRouteImport } from './routes/dashboard/governance/audits/$auditId'

const ForgetPasswordLazyRouteImport = createFileRoute('/forget-password')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const AuthLazyRouteImport = createFileRoute('/auth')()
const AuthSignupLazyRouteImport = createFileRoute('/auth/signup')()
const AuthLoginLazyRouteImport = createFileRoute('/auth/login')()

const ForgetPasswordLazyRoute = ForgetPasswordLazyRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forget-password.lazy').then((d) => d.Route),
)
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const AuthLazyRoute = AuthLazyRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLazyRoute,
} as any)
const AuthSignupLazyRoute = AuthSignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/signup.lazy').then((d) => d.Route))
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings.lazy').then((d) => d.Route),
)
const DashboardSocialTrainingCompletionRoute =
  DashboardSocialTrainingCompletionRouteImport.update({
    id: '/social/training-completion',
    path: '/social/training-completion',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardSocialOverviewRoute = DashboardSocialOverviewRouteImport.update({
  id: '/social/overview',
  path: '/social/overview',
  getParentRoute: () => DashboardLazyRoute,
} as any)
const DashboardSocialEmployeeParticipationRoute =
  DashboardSocialEmployeeParticipationRouteImport.update({
    id: '/social/employee-participation',
    path: '/social/employee-participation',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardSocialDiversityMetricsRoute =
  DashboardSocialDiversityMetricsRouteImport.update({
    id: '/social/diversity-metrics',
    path: '/social/diversity-metrics',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernancePolicyAcknowledgementsRoute =
  DashboardGovernancePolicyAcknowledgementsRouteImport.update({
    id: '/governance/policy-acknowledgements',
    path: '/governance/policy-acknowledgements',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernanceOverviewRoute =
  DashboardGovernanceOverviewRouteImport.update({
    id: '/governance/overview',
    path: '/governance/overview',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGamificationRewardsRoute =
  DashboardGamificationRewardsRouteImport.update({
    id: '/gamification/rewards',
    path: '/gamification/rewards',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGamificationRedemptionsRoute =
  DashboardGamificationRedemptionsRouteImport.update({
    id: '/gamification/redemptions',
    path: '/gamification/redemptions',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGamificationParticipationApprovalsRoute =
  DashboardGamificationParticipationApprovalsRouteImport.update({
    id: '/gamification/participation-approvals',
    path: '/gamification/participation-approvals',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGamificationLeaderboardRoute =
  DashboardGamificationLeaderboardRouteImport.update({
    id: '/gamification/leaderboard',
    path: '/gamification/leaderboard',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGamificationChallengesRoute =
  DashboardGamificationChallengesRouteImport.update({
    id: '/gamification/challenges',
    path: '/gamification/challenges',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGamificationBadgesRoute =
  DashboardGamificationBadgesRouteImport.update({
    id: '/gamification/badges',
    path: '/gamification/badges',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardEnvironmentalSustainabilityGoalsRoute =
  DashboardEnvironmentalSustainabilityGoalsRouteImport.update({
    id: '/environmental/sustainability-goals',
    path: '/environmental/sustainability-goals',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardEnvironmentalProductEsgProfilesRoute =
  DashboardEnvironmentalProductEsgProfilesRouteImport.update({
    id: '/environmental/product-esg-profiles',
    path: '/environmental/product-esg-profiles',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardEnvironmentalOverviewRoute =
  DashboardEnvironmentalOverviewRouteImport.update({
    id: '/environmental/overview',
    path: '/environmental/overview',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardEnvironmentalEmissionFactorsRoute =
  DashboardEnvironmentalEmissionFactorsRouteImport.update({
    id: '/environmental/emission-factors',
    path: '/environmental/emission-factors',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardEnvironmentalCarbonTransactionsRoute =
  DashboardEnvironmentalCarbonTransactionsRouteImport.update({
    id: '/environmental/carbon-transactions',
    path: '/environmental/carbon-transactions',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardAdministrationNotificationSettingsRoute =
  DashboardAdministrationNotificationSettingsRouteImport.update({
    id: '/administration/notification-settings',
    path: '/administration/notification-settings',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardAdministrationEsgConfigurationRoute =
  DashboardAdministrationEsgConfigurationRouteImport.update({
    id: '/administration/esg-configuration',
    path: '/administration/esg-configuration',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardAdministrationDepartmentsRoute =
  DashboardAdministrationDepartmentsRouteImport.update({
    id: '/administration/departments',
    path: '/administration/departments',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardAdministrationCategoriesRoute =
  DashboardAdministrationCategoriesRouteImport.update({
    id: '/administration/categories',
    path: '/administration/categories',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardSocialCsrActivitiesIndexRoute =
  DashboardSocialCsrActivitiesIndexRouteImport.update({
    id: '/social/csr-activities/',
    path: '/social/csr-activities/',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernancePoliciesIndexRoute =
  DashboardGovernancePoliciesIndexRouteImport.update({
    id: '/governance/policies/',
    path: '/governance/policies/',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernanceComplianceIssuesIndexRoute =
  DashboardGovernanceComplianceIssuesIndexRouteImport.update({
    id: '/governance/compliance-issues/',
    path: '/governance/compliance-issues/',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernanceAuditsIndexRoute =
  DashboardGovernanceAuditsIndexRouteImport.update({
    id: '/governance/audits/',
    path: '/governance/audits/',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardSocialCsrActivitiesActivityIdRoute =
  DashboardSocialCsrActivitiesActivityIdRouteImport.update({
    id: '/social/csr-activities/$activityId',
    path: '/social/csr-activities/$activityId',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernancePoliciesPolicyIdRoute =
  DashboardGovernancePoliciesPolicyIdRouteImport.update({
    id: '/governance/policies/$policyId',
    path: '/governance/policies/$policyId',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernanceComplianceIssuesIssueIdRoute =
  DashboardGovernanceComplianceIssuesIssueIdRouteImport.update({
    id: '/governance/compliance-issues/$issueId',
    path: '/governance/compliance-issues/$issueId',
    getParentRoute: () => DashboardLazyRoute,
  } as any)
const DashboardGovernanceAuditsAuditIdRoute =
  DashboardGovernanceAuditsAuditIdRouteImport.update({
    id: '/governance/audits/$auditId',
    path: '/governance/audits/$auditId',
    getParentRoute: () => DashboardLazyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/administration/categories': typeof DashboardAdministrationCategoriesRoute
  '/dashboard/administration/departments': typeof DashboardAdministrationDepartmentsRoute
  '/dashboard/administration/esg-configuration': typeof DashboardAdministrationEsgConfigurationRoute
  '/dashboard/administration/notification-settings': typeof DashboardAdministrationNotificationSettingsRoute
  '/dashboard/environmental/carbon-transactions': typeof DashboardEnvironmentalCarbonTransactionsRoute
  '/dashboard/environmental/emission-factors': typeof DashboardEnvironmentalEmissionFactorsRoute
  '/dashboard/environmental/overview': typeof DashboardEnvironmentalOverviewRoute
  '/dashboard/environmental/product-esg-profiles': typeof DashboardEnvironmentalProductEsgProfilesRoute
  '/dashboard/environmental/sustainability-goals': typeof DashboardEnvironmentalSustainabilityGoalsRoute
  '/dashboard/gamification/badges': typeof DashboardGamificationBadgesRoute
  '/dashboard/gamification/challenges': typeof DashboardGamificationChallengesRoute
  '/dashboard/gamification/leaderboard': typeof DashboardGamificationLeaderboardRoute
  '/dashboard/gamification/participation-approvals': typeof DashboardGamificationParticipationApprovalsRoute
  '/dashboard/gamification/redemptions': typeof DashboardGamificationRedemptionsRoute
  '/dashboard/gamification/rewards': typeof DashboardGamificationRewardsRoute
  '/dashboard/governance/overview': typeof DashboardGovernanceOverviewRoute
  '/dashboard/governance/policy-acknowledgements': typeof DashboardGovernancePolicyAcknowledgementsRoute
  '/dashboard/social/diversity-metrics': typeof DashboardSocialDiversityMetricsRoute
  '/dashboard/social/employee-participation': typeof DashboardSocialEmployeeParticipationRoute
  '/dashboard/social/overview': typeof DashboardSocialOverviewRoute
  '/dashboard/social/training-completion': typeof DashboardSocialTrainingCompletionRoute
  '/dashboard/governance/audits/$auditId': typeof DashboardGovernanceAuditsAuditIdRoute
  '/dashboard/governance/compliance-issues/$issueId': typeof DashboardGovernanceComplianceIssuesIssueIdRoute
  '/dashboard/governance/policies/$policyId': typeof DashboardGovernancePoliciesPolicyIdRoute
  '/dashboard/social/csr-activities/$activityId': typeof DashboardSocialCsrActivitiesActivityIdRoute
  '/dashboard/governance/audits/': typeof DashboardGovernanceAuditsIndexRoute
  '/dashboard/governance/compliance-issues/': typeof DashboardGovernanceComplianceIssuesIndexRoute
  '/dashboard/governance/policies/': typeof DashboardGovernancePoliciesIndexRoute
  '/dashboard/social/csr-activities/': typeof DashboardSocialCsrActivitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/administration/categories': typeof DashboardAdministrationCategoriesRoute
  '/dashboard/administration/departments': typeof DashboardAdministrationDepartmentsRoute
  '/dashboard/administration/esg-configuration': typeof DashboardAdministrationEsgConfigurationRoute
  '/dashboard/administration/notification-settings': typeof DashboardAdministrationNotificationSettingsRoute
  '/dashboard/environmental/carbon-transactions': typeof DashboardEnvironmentalCarbonTransactionsRoute
  '/dashboard/environmental/emission-factors': typeof DashboardEnvironmentalEmissionFactorsRoute
  '/dashboard/environmental/overview': typeof DashboardEnvironmentalOverviewRoute
  '/dashboard/environmental/product-esg-profiles': typeof DashboardEnvironmentalProductEsgProfilesRoute
  '/dashboard/environmental/sustainability-goals': typeof DashboardEnvironmentalSustainabilityGoalsRoute
  '/dashboard/gamification/badges': typeof DashboardGamificationBadgesRoute
  '/dashboard/gamification/challenges': typeof DashboardGamificationChallengesRoute
  '/dashboard/gamification/leaderboard': typeof DashboardGamificationLeaderboardRoute
  '/dashboard/gamification/participation-approvals': typeof DashboardGamificationParticipationApprovalsRoute
  '/dashboard/gamification/redemptions': typeof DashboardGamificationRedemptionsRoute
  '/dashboard/gamification/rewards': typeof DashboardGamificationRewardsRoute
  '/dashboard/governance/overview': typeof DashboardGovernanceOverviewRoute
  '/dashboard/governance/policy-acknowledgements': typeof DashboardGovernancePolicyAcknowledgementsRoute
  '/dashboard/social/diversity-metrics': typeof DashboardSocialDiversityMetricsRoute
  '/dashboard/social/employee-participation': typeof DashboardSocialEmployeeParticipationRoute
  '/dashboard/social/overview': typeof DashboardSocialOverviewRoute
  '/dashboard/social/training-completion': typeof DashboardSocialTrainingCompletionRoute
  '/dashboard/governance/audits/$auditId': typeof DashboardGovernanceAuditsAuditIdRoute
  '/dashboard/governance/compliance-issues/$issueId': typeof DashboardGovernanceComplianceIssuesIssueIdRoute
  '/dashboard/governance/policies/$policyId': typeof DashboardGovernancePoliciesPolicyIdRoute
  '/dashboard/social/csr-activities/$activityId': typeof DashboardSocialCsrActivitiesActivityIdRoute
  '/dashboard/governance/audits': typeof DashboardGovernanceAuditsIndexRoute
  '/dashboard/governance/compliance-issues': typeof DashboardGovernanceComplianceIssuesIndexRoute
  '/dashboard/governance/policies': typeof DashboardGovernancePoliciesIndexRoute
  '/dashboard/social/csr-activities': typeof DashboardSocialCsrActivitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/forget-password': typeof ForgetPasswordLazyRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/administration/categories': typeof DashboardAdministrationCategoriesRoute
  '/dashboard/administration/departments': typeof DashboardAdministrationDepartmentsRoute
  '/dashboard/administration/esg-configuration': typeof DashboardAdministrationEsgConfigurationRoute
  '/dashboard/administration/notification-settings': typeof DashboardAdministrationNotificationSettingsRoute
  '/dashboard/environmental/carbon-transactions': typeof DashboardEnvironmentalCarbonTransactionsRoute
  '/dashboard/environmental/emission-factors': typeof DashboardEnvironmentalEmissionFactorsRoute
  '/dashboard/environmental/overview': typeof DashboardEnvironmentalOverviewRoute
  '/dashboard/environmental/product-esg-profiles': typeof DashboardEnvironmentalProductEsgProfilesRoute
  '/dashboard/environmental/sustainability-goals': typeof DashboardEnvironmentalSustainabilityGoalsRoute
  '/dashboard/gamification/badges': typeof DashboardGamificationBadgesRoute
  '/dashboard/gamification/challenges': typeof DashboardGamificationChallengesRoute
  '/dashboard/gamification/leaderboard': typeof DashboardGamificationLeaderboardRoute
  '/dashboard/gamification/participation-approvals': typeof DashboardGamificationParticipationApprovalsRoute
  '/dashboard/gamification/redemptions': typeof DashboardGamificationRedemptionsRoute
  '/dashboard/gamification/rewards': typeof DashboardGamificationRewardsRoute
  '/dashboard/governance/overview': typeof DashboardGovernanceOverviewRoute
  '/dashboard/governance/policy-acknowledgements': typeof DashboardGovernancePolicyAcknowledgementsRoute
  '/dashboard/social/diversity-metrics': typeof DashboardSocialDiversityMetricsRoute
  '/dashboard/social/employee-participation': typeof DashboardSocialEmployeeParticipationRoute
  '/dashboard/social/overview': typeof DashboardSocialOverviewRoute
  '/dashboard/social/training-completion': typeof DashboardSocialTrainingCompletionRoute
  '/dashboard/governance/audits/$auditId': typeof DashboardGovernanceAuditsAuditIdRoute
  '/dashboard/governance/compliance-issues/$issueId': typeof DashboardGovernanceComplianceIssuesIssueIdRoute
  '/dashboard/governance/policies/$policyId': typeof DashboardGovernancePoliciesPolicyIdRoute
  '/dashboard/social/csr-activities/$activityId': typeof DashboardSocialCsrActivitiesActivityIdRoute
  '/dashboard/governance/audits/': typeof DashboardGovernanceAuditsIndexRoute
  '/dashboard/governance/compliance-issues/': typeof DashboardGovernanceComplianceIssuesIndexRoute
  '/dashboard/governance/policies/': typeof DashboardGovernancePoliciesIndexRoute
  '/dashboard/social/csr-activities/': typeof DashboardSocialCsrActivitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forget-password'
    | '/dashboard/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/dashboard/administration/categories'
    | '/dashboard/administration/departments'
    | '/dashboard/administration/esg-configuration'
    | '/dashboard/administration/notification-settings'
    | '/dashboard/environmental/carbon-transactions'
    | '/dashboard/environmental/emission-factors'
    | '/dashboard/environmental/overview'
    | '/dashboard/environmental/product-esg-profiles'
    | '/dashboard/environmental/sustainability-goals'
    | '/dashboard/gamification/badges'
    | '/dashboard/gamification/challenges'
    | '/dashboard/gamification/leaderboard'
    | '/dashboard/gamification/participation-approvals'
    | '/dashboard/gamification/redemptions'
    | '/dashboard/gamification/rewards'
    | '/dashboard/governance/overview'
    | '/dashboard/governance/policy-acknowledgements'
    | '/dashboard/social/diversity-metrics'
    | '/dashboard/social/employee-participation'
    | '/dashboard/social/overview'
    | '/dashboard/social/training-completion'
    | '/dashboard/governance/audits/$auditId'
    | '/dashboard/governance/compliance-issues/$issueId'
    | '/dashboard/governance/policies/$policyId'
    | '/dashboard/social/csr-activities/$activityId'
    | '/dashboard/governance/audits/'
    | '/dashboard/governance/compliance-issues/'
    | '/dashboard/governance/policies/'
    | '/dashboard/social/csr-activities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forget-password'
    | '/dashboard/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard'
    | '/dashboard/administration/categories'
    | '/dashboard/administration/departments'
    | '/dashboard/administration/esg-configuration'
    | '/dashboard/administration/notification-settings'
    | '/dashboard/environmental/carbon-transactions'
    | '/dashboard/environmental/emission-factors'
    | '/dashboard/environmental/overview'
    | '/dashboard/environmental/product-esg-profiles'
    | '/dashboard/environmental/sustainability-goals'
    | '/dashboard/gamification/badges'
    | '/dashboard/gamification/challenges'
    | '/dashboard/gamification/leaderboard'
    | '/dashboard/gamification/participation-approvals'
    | '/dashboard/gamification/redemptions'
    | '/dashboard/gamification/rewards'
    | '/dashboard/governance/overview'
    | '/dashboard/governance/policy-acknowledgements'
    | '/dashboard/social/diversity-metrics'
    | '/dashboard/social/employee-participation'
    | '/dashboard/social/overview'
    | '/dashboard/social/training-completion'
    | '/dashboard/governance/audits/$auditId'
    | '/dashboard/governance/compliance-issues/$issueId'
    | '/dashboard/governance/policies/$policyId'
    | '/dashboard/social/csr-activities/$activityId'
    | '/dashboard/governance/audits'
    | '/dashboard/governance/compliance-issues'
    | '/dashboard/governance/policies'
    | '/dashboard/social/csr-activities'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forget-password'
    | '/dashboard/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
    | '/dashboard/administration/categories'
    | '/dashboard/administration/departments'
    | '/dashboard/administration/esg-configuration'
    | '/dashboard/administration/notification-settings'
    | '/dashboard/environmental/carbon-transactions'
    | '/dashboard/environmental/emission-factors'
    | '/dashboard/environmental/overview'
    | '/dashboard/environmental/product-esg-profiles'
    | '/dashboard/environmental/sustainability-goals'
    | '/dashboard/gamification/badges'
    | '/dashboard/gamification/challenges'
    | '/dashboard/gamification/leaderboard'
    | '/dashboard/gamification/participation-approvals'
    | '/dashboard/gamification/redemptions'
    | '/dashboard/gamification/rewards'
    | '/dashboard/governance/overview'
    | '/dashboard/governance/policy-acknowledgements'
    | '/dashboard/social/diversity-metrics'
    | '/dashboard/social/employee-participation'
    | '/dashboard/social/overview'
    | '/dashboard/social/training-completion'
    | '/dashboard/governance/audits/$auditId'
    | '/dashboard/governance/compliance-issues/$issueId'
    | '/dashboard/governance/policies/$policyId'
    | '/dashboard/social/csr-activities/$activityId'
    | '/dashboard/governance/audits/'
    | '/dashboard/governance/compliance-issues/'
    | '/dashboard/governance/policies/'
    | '/dashboard/social/csr-activities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLazyRoute: typeof AuthLazyRouteWithChildren
  DashboardLazyRoute: typeof DashboardLazyRouteWithChildren
  ForgetPasswordLazyRoute: typeof ForgetPasswordLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forget-password': {
      id: '/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof ForgetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof AuthLazyRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/social/training-completion': {
      id: '/dashboard/social/training-completion'
      path: '/social/training-completion'
      fullPath: '/dashboard/social/training-completion'
      preLoaderRoute: typeof DashboardSocialTrainingCompletionRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/social/overview': {
      id: '/dashboard/social/overview'
      path: '/social/overview'
      fullPath: '/dashboard/social/overview'
      preLoaderRoute: typeof DashboardSocialOverviewRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/social/employee-participation': {
      id: '/dashboard/social/employee-participation'
      path: '/social/employee-participation'
      fullPath: '/dashboard/social/employee-participation'
      preLoaderRoute: typeof DashboardSocialEmployeeParticipationRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/social/diversity-metrics': {
      id: '/dashboard/social/diversity-metrics'
      path: '/social/diversity-metrics'
      fullPath: '/dashboard/social/diversity-metrics'
      preLoaderRoute: typeof DashboardSocialDiversityMetricsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/policy-acknowledgements': {
      id: '/dashboard/governance/policy-acknowledgements'
      path: '/governance/policy-acknowledgements'
      fullPath: '/dashboard/governance/policy-acknowledgements'
      preLoaderRoute: typeof DashboardGovernancePolicyAcknowledgementsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/overview': {
      id: '/dashboard/governance/overview'
      path: '/governance/overview'
      fullPath: '/dashboard/governance/overview'
      preLoaderRoute: typeof DashboardGovernanceOverviewRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/gamification/rewards': {
      id: '/dashboard/gamification/rewards'
      path: '/gamification/rewards'
      fullPath: '/dashboard/gamification/rewards'
      preLoaderRoute: typeof DashboardGamificationRewardsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/gamification/redemptions': {
      id: '/dashboard/gamification/redemptions'
      path: '/gamification/redemptions'
      fullPath: '/dashboard/gamification/redemptions'
      preLoaderRoute: typeof DashboardGamificationRedemptionsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/gamification/participation-approvals': {
      id: '/dashboard/gamification/participation-approvals'
      path: '/gamification/participation-approvals'
      fullPath: '/dashboard/gamification/participation-approvals'
      preLoaderRoute: typeof DashboardGamificationParticipationApprovalsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/gamification/leaderboard': {
      id: '/dashboard/gamification/leaderboard'
      path: '/gamification/leaderboard'
      fullPath: '/dashboard/gamification/leaderboard'
      preLoaderRoute: typeof DashboardGamificationLeaderboardRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/gamification/challenges': {
      id: '/dashboard/gamification/challenges'
      path: '/gamification/challenges'
      fullPath: '/dashboard/gamification/challenges'
      preLoaderRoute: typeof DashboardGamificationChallengesRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/gamification/badges': {
      id: '/dashboard/gamification/badges'
      path: '/gamification/badges'
      fullPath: '/dashboard/gamification/badges'
      preLoaderRoute: typeof DashboardGamificationBadgesRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/environmental/sustainability-goals': {
      id: '/dashboard/environmental/sustainability-goals'
      path: '/environmental/sustainability-goals'
      fullPath: '/dashboard/environmental/sustainability-goals'
      preLoaderRoute: typeof DashboardEnvironmentalSustainabilityGoalsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/environmental/product-esg-profiles': {
      id: '/dashboard/environmental/product-esg-profiles'
      path: '/environmental/product-esg-profiles'
      fullPath: '/dashboard/environmental/product-esg-profiles'
      preLoaderRoute: typeof DashboardEnvironmentalProductEsgProfilesRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/environmental/overview': {
      id: '/dashboard/environmental/overview'
      path: '/environmental/overview'
      fullPath: '/dashboard/environmental/overview'
      preLoaderRoute: typeof DashboardEnvironmentalOverviewRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/environmental/emission-factors': {
      id: '/dashboard/environmental/emission-factors'
      path: '/environmental/emission-factors'
      fullPath: '/dashboard/environmental/emission-factors'
      preLoaderRoute: typeof DashboardEnvironmentalEmissionFactorsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/environmental/carbon-transactions': {
      id: '/dashboard/environmental/carbon-transactions'
      path: '/environmental/carbon-transactions'
      fullPath: '/dashboard/environmental/carbon-transactions'
      preLoaderRoute: typeof DashboardEnvironmentalCarbonTransactionsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/administration/notification-settings': {
      id: '/dashboard/administration/notification-settings'
      path: '/administration/notification-settings'
      fullPath: '/dashboard/administration/notification-settings'
      preLoaderRoute: typeof DashboardAdministrationNotificationSettingsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/administration/esg-configuration': {
      id: '/dashboard/administration/esg-configuration'
      path: '/administration/esg-configuration'
      fullPath: '/dashboard/administration/esg-configuration'
      preLoaderRoute: typeof DashboardAdministrationEsgConfigurationRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/administration/departments': {
      id: '/dashboard/administration/departments'
      path: '/administration/departments'
      fullPath: '/dashboard/administration/departments'
      preLoaderRoute: typeof DashboardAdministrationDepartmentsRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/administration/categories': {
      id: '/dashboard/administration/categories'
      path: '/administration/categories'
      fullPath: '/dashboard/administration/categories'
      preLoaderRoute: typeof DashboardAdministrationCategoriesRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/social/csr-activities/': {
      id: '/dashboard/social/csr-activities/'
      path: '/social/csr-activities'
      fullPath: '/dashboard/social/csr-activities/'
      preLoaderRoute: typeof DashboardSocialCsrActivitiesIndexRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/policies/': {
      id: '/dashboard/governance/policies/'
      path: '/governance/policies'
      fullPath: '/dashboard/governance/policies/'
      preLoaderRoute: typeof DashboardGovernancePoliciesIndexRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/compliance-issues/': {
      id: '/dashboard/governance/compliance-issues/'
      path: '/governance/compliance-issues'
      fullPath: '/dashboard/governance/compliance-issues/'
      preLoaderRoute: typeof DashboardGovernanceComplianceIssuesIndexRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/audits/': {
      id: '/dashboard/governance/audits/'
      path: '/governance/audits'
      fullPath: '/dashboard/governance/audits/'
      preLoaderRoute: typeof DashboardGovernanceAuditsIndexRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/social/csr-activities/$activityId': {
      id: '/dashboard/social/csr-activities/$activityId'
      path: '/social/csr-activities/$activityId'
      fullPath: '/dashboard/social/csr-activities/$activityId'
      preLoaderRoute: typeof DashboardSocialCsrActivitiesActivityIdRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/policies/$policyId': {
      id: '/dashboard/governance/policies/$policyId'
      path: '/governance/policies/$policyId'
      fullPath: '/dashboard/governance/policies/$policyId'
      preLoaderRoute: typeof DashboardGovernancePoliciesPolicyIdRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/compliance-issues/$issueId': {
      id: '/dashboard/governance/compliance-issues/$issueId'
      path: '/governance/compliance-issues/$issueId'
      fullPath: '/dashboard/governance/compliance-issues/$issueId'
      preLoaderRoute: typeof DashboardGovernanceComplianceIssuesIssueIdRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/governance/audits/$auditId': {
      id: '/dashboard/governance/audits/$auditId'
      path: '/governance/audits/$auditId'
      fullPath: '/dashboard/governance/audits/$auditId'
      preLoaderRoute: typeof DashboardGovernanceAuditsAuditIdRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
  }
}

interface AuthLazyRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthSignupLazyRoute: typeof AuthSignupLazyRoute
}

const AuthLazyRouteChildren: AuthLazyRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthSignupLazyRoute: AuthSignupLazyRoute,
}

const AuthLazyRouteWithChildren = AuthLazyRoute._addFileChildren(
  AuthLazyRouteChildren,
)

interface DashboardLazyRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdministrationCategoriesRoute: typeof DashboardAdministrationCategoriesRoute
  DashboardAdministrationDepartmentsRoute: typeof DashboardAdministrationDepartmentsRoute
  DashboardAdministrationEsgConfigurationRoute: typeof DashboardAdministrationEsgConfigurationRoute
  DashboardAdministrationNotificationSettingsRoute: typeof DashboardAdministrationNotificationSettingsRoute
  DashboardEnvironmentalCarbonTransactionsRoute: typeof DashboardEnvironmentalCarbonTransactionsRoute
  DashboardEnvironmentalEmissionFactorsRoute: typeof DashboardEnvironmentalEmissionFactorsRoute
  DashboardEnvironmentalOverviewRoute: typeof DashboardEnvironmentalOverviewRoute
  DashboardEnvironmentalProductEsgProfilesRoute: typeof DashboardEnvironmentalProductEsgProfilesRoute
  DashboardEnvironmentalSustainabilityGoalsRoute: typeof DashboardEnvironmentalSustainabilityGoalsRoute
  DashboardGamificationBadgesRoute: typeof DashboardGamificationBadgesRoute
  DashboardGamificationChallengesRoute: typeof DashboardGamificationChallengesRoute
  DashboardGamificationLeaderboardRoute: typeof DashboardGamificationLeaderboardRoute
  DashboardGamificationParticipationApprovalsRoute: typeof DashboardGamificationParticipationApprovalsRoute
  DashboardGamificationRedemptionsRoute: typeof DashboardGamificationRedemptionsRoute
  DashboardGamificationRewardsRoute: typeof DashboardGamificationRewardsRoute
  DashboardGovernanceOverviewRoute: typeof DashboardGovernanceOverviewRoute
  DashboardGovernancePolicyAcknowledgementsRoute: typeof DashboardGovernancePolicyAcknowledgementsRoute
  DashboardSocialDiversityMetricsRoute: typeof DashboardSocialDiversityMetricsRoute
  DashboardSocialEmployeeParticipationRoute: typeof DashboardSocialEmployeeParticipationRoute
  DashboardSocialOverviewRoute: typeof DashboardSocialOverviewRoute
  DashboardSocialTrainingCompletionRoute: typeof DashboardSocialTrainingCompletionRoute
  DashboardGovernanceAuditsAuditIdRoute: typeof DashboardGovernanceAuditsAuditIdRoute
  DashboardGovernanceComplianceIssuesIssueIdRoute: typeof DashboardGovernanceComplianceIssuesIssueIdRoute
  DashboardGovernancePoliciesPolicyIdRoute: typeof DashboardGovernancePoliciesPolicyIdRoute
  DashboardSocialCsrActivitiesActivityIdRoute: typeof DashboardSocialCsrActivitiesActivityIdRoute
  DashboardGovernanceAuditsIndexRoute: typeof DashboardGovernanceAuditsIndexRoute
  DashboardGovernanceComplianceIssuesIndexRoute: typeof DashboardGovernanceComplianceIssuesIndexRoute
  DashboardGovernancePoliciesIndexRoute: typeof DashboardGovernancePoliciesIndexRoute
  DashboardSocialCsrActivitiesIndexRoute: typeof DashboardSocialCsrActivitiesIndexRoute
}

const DashboardLazyRouteChildren: DashboardLazyRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdministrationCategoriesRoute:
    DashboardAdministrationCategoriesRoute,
  DashboardAdministrationDepartmentsRoute:
    DashboardAdministrationDepartmentsRoute,
  DashboardAdministrationEsgConfigurationRoute:
    DashboardAdministrationEsgConfigurationRoute,
  DashboardAdministrationNotificationSettingsRoute:
    DashboardAdministrationNotificationSettingsRoute,
  DashboardEnvironmentalCarbonTransactionsRoute:
    DashboardEnvironmentalCarbonTransactionsRoute,
  DashboardEnvironmentalEmissionFactorsRoute:
    DashboardEnvironmentalEmissionFactorsRoute,
  DashboardEnvironmentalOverviewRoute: DashboardEnvironmentalOverviewRoute,
  DashboardEnvironmentalProductEsgProfilesRoute:
    DashboardEnvironmentalProductEsgProfilesRoute,
  DashboardEnvironmentalSustainabilityGoalsRoute:
    DashboardEnvironmentalSustainabilityGoalsRoute,
  DashboardGamificationBadgesRoute: DashboardGamificationBadgesRoute,
  DashboardGamificationChallengesRoute: DashboardGamificationChallengesRoute,
  DashboardGamificationLeaderboardRoute: DashboardGamificationLeaderboardRoute,
  DashboardGamificationParticipationApprovalsRoute:
    DashboardGamificationParticipationApprovalsRoute,
  DashboardGamificationRedemptionsRoute: DashboardGamificationRedemptionsRoute,
  DashboardGamificationRewardsRoute: DashboardGamificationRewardsRoute,
  DashboardGovernanceOverviewRoute: DashboardGovernanceOverviewRoute,
  DashboardGovernancePolicyAcknowledgementsRoute:
    DashboardGovernancePolicyAcknowledgementsRoute,
  DashboardSocialDiversityMetricsRoute: DashboardSocialDiversityMetricsRoute,
  DashboardSocialEmployeeParticipationRoute:
    DashboardSocialEmployeeParticipationRoute,
  DashboardSocialOverviewRoute: DashboardSocialOverviewRoute,
  DashboardSocialTrainingCompletionRoute:
    DashboardSocialTrainingCompletionRoute,
  DashboardGovernanceAuditsAuditIdRoute: DashboardGovernanceAuditsAuditIdRoute,
  DashboardGovernanceComplianceIssuesIssueIdRoute:
    DashboardGovernanceComplianceIssuesIssueIdRoute,
  DashboardGovernancePoliciesPolicyIdRoute:
    DashboardGovernancePoliciesPolicyIdRoute,
  DashboardSocialCsrActivitiesActivityIdRoute:
    DashboardSocialCsrActivitiesActivityIdRoute,
  DashboardGovernanceAuditsIndexRoute: DashboardGovernanceAuditsIndexRoute,
  DashboardGovernanceComplianceIssuesIndexRoute:
    DashboardGovernanceComplianceIssuesIndexRoute,
  DashboardGovernancePoliciesIndexRoute: DashboardGovernancePoliciesIndexRoute,
  DashboardSocialCsrActivitiesIndexRoute:
    DashboardSocialCsrActivitiesIndexRoute,
}

const DashboardLazyRouteWithChildren = DashboardLazyRoute._addFileChildren(
  DashboardLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLazyRoute: AuthLazyRouteWithChildren,
  DashboardLazyRoute: DashboardLazyRouteWithChildren,
  ForgetPasswordLazyRoute: ForgetPasswordLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
